Merging local config feature
stork119/PathwayPackage pull request #114
Opened 2017-03-21 09:55 UTC by Setnea

2017-03-21 12:07 UTC, stork119 requested changes
Look at my doubts about style and IPIQA.xml

2017-03-21 12:07 UTC, stork119 commented on config/IPIQA.xml
> +    <parameter key="experiment_finished" value="True"/>
number_of_cores and number_of_cores don't describe parameters of computer, but rather execution. Please, remove them from IPIQA.xml

2017-03-21 12:07 UTC, stork119 commented on python/WorkflowEngine.py
> +    if args.a != False: # optional argument
@Setnea why we cannot write ?: 
```
if args.a:
    additional_arg = {(args.a[0]) : (args.a[1])}
``` 

https://google.github.io/styleguide/pyguide.html?showone=True/False_evaluations#True/False_evaluations

2017-03-21 12:07 UTC, stork119 commented on python/WorkflowEngine.py
> +    if args.c != False: # optional (additional) config
same

2017-03-21 12:53 UTC, Setnea commented on config/IPIQA.xml
> +    <parameter key="experiment_finished" value="True"/>
Fixed.

2017-03-21 12:55 UTC, Setnea commented on python/WorkflowEngine.py
> +    if args.a != False: # optional argument
@stork119 Lol, you're right, silly me.

2017-03-21 12:55 UTC, Setnea commented on python/WorkflowEngine.py
> +    if args.c != False: # optional (additional) config
same

2017-03-23 09:55 UTC, stork119 approved these changes

2017-03-23 11:49 UTC, merged

2017-03-23 11:55 UTC, Setnea commented
I'm gonna delete branch in the evening, I have to check out sth.