Hotfix_tests into develop
stork119/PathwayPackage pull request #125
Opened 2017-03-30 07:33 UTC by Setnea

Adding test6 version working with map_plate changes.

2017-03-30 13:21 UTC, stork119 requested changes
Tests have commented parts.

2017-03-30 13:21 UTC, stork119 commented on tests/release/configuration_settings/2017-02-14-t2.xml
> +                        <TASK class="TASK_REMOVE">
It should not be commented

2017-03-30 13:34 UTC, Setnea commented
Right, I probably was testing sth; temporary commented to speed up process and forgot to uncomment before push. Gonna be more carefull next time.

2017-03-31 07:35 UTC, stork119 requested changes
position.name -> id

2017-03-31 11:41 UTC, Setnea commented
Everything works fine now. May I merge?

2017-04-03 10:01 UTC, stork119 approved these changes

2017-04-03 10:04 UTC, merged