Python_module into develop
stork119/PathwayPackage pull request #167
Opened 2017-05-31 13:54 UTC by Setnea

2017-05-31 14:45 UTC, stork119 requested changes
@Setnea  try to answer on my questions

2017-05-31 14:45 UTC, stork119 commented on python/modules/task.py
> +        output_dict = python_connection.execute_python_script(param_dict, dict_setts["python_script_path"], dict_setts["python_function_name"])
Lines are too long, add some enters

2017-05-31 14:45 UTC, stork119 commented on python/modules/python_connection.py
> +    p_source = importlib.util.spec_from_file_location("external_module", python_script_path)
Add some comment this function. How script should look like ? Do you load python script and then execute functions that are there ? 
What if python script is bigger than one file ?

2017-06-02 12:45 UTC, Setnea commented on python/modules/task.py
> +        output_dict = python_connection.execute_python_script(param_dict, dict_setts["python_script_path"], dict_setts["python_function_name"])
Fixed, where possible.

2017-06-02 12:45 UTC, stork119 approved these changes

2017-06-02 12:49 UTC, Setnea commented on python/modules/python_connection.py
> +    p_source = importlib.util.spec_from_file_location("external_module", python_script_path)
Added some comments which explains how to use module. 
Yes, I load it as module, get an assigment for function with defined name and than execute it.
If scripts are bigger than one file, user should take care of proper imports i.e. import other modules by using their absolute paths. Now I'm kinda curious how does it work when it comes to r_connection.

2017-06-02 12:49 UTC, merged